# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtUi\agregarpaciente.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 570)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.send = QtWidgets.QPushButton(self.centralWidget)
        self.send.setGeometry(QtCore.QRect(120, 390, 141, 61))
        self.send.setObjectName("send")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(340, 40, 141, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(570, 130, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(30, 160, 61, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(30, 200, 61, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(560, 240, 41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gender = QtWidgets.QComboBox(self.centralWidget)
        self.gender.setGeometry(QtCore.QRect(630, 240, 111, 27))
        self.gender.setObjectName("gender")
        self.dateEdit = QtWidgets.QDateEdit(self.centralWidget)
        self.dateEdit.setGeometry(QtCore.QRect(170, 240, 191, 27))
        self.dateEdit.setObjectName("dateEdit")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(30, 240, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.ti = QtWidgets.QComboBox(self.centralWidget)
        self.ti.setGeometry(QtCore.QRect(600, 120, 141, 31))
        self.ti.setObjectName("ti")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(30, 280, 61, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.spinBox = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox.setGeometry(QtCore.QRect(440, 240, 101, 22))
        self.spinBox.setObjectName("spinBox")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(390, 240, 31, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.clean = QtWidgets.QPushButton(self.centralWidget)
        self.clean.setGeometry(QtCore.QRect(600, 390, 141, 61))
        self.clean.setObjectName("clean")
        self.idp = QtWidgets.QTextEdit(self.centralWidget)
        self.idp.setGeometry(QtCore.QRect(120, 120, 441, 31))
        self.idp.setObjectName("idp")
        self.name = QtWidgets.QTextEdit(self.centralWidget)
        self.name.setGeometry(QtCore.QRect(120, 160, 621, 31))
        self.name.setObjectName("name")
        self.last = QtWidgets.QTextEdit(self.centralWidget)
        self.last.setGeometry(QtCore.QRect(120, 200, 621, 31))
        self.last.setObjectName("last")
        self.phone = QtWidgets.QTextEdit(self.centralWidget)
        self.phone.setGeometry(QtCore.QRect(120, 280, 261, 31))
        self.phone.setObjectName("phone")
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 806, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuOpciones = QtWidgets.QMenu(self.menuBar)
        self.menuOpciones.setObjectName("menuOpciones")
        MainWindow.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menuOpciones.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Agregar paciente"))
        self.send.setText(_translate("MainWindow", "Enviar"))
        self.label.setText(_translate("MainWindow", "Paciente"))
        self.label_3.setText(_translate("MainWindow", "TI"))
        self.label_4.setText(_translate("MainWindow", "Nombres"))
        self.label_5.setText(_translate("MainWindow", "Apellidos"))
        self.label_6.setText(_translate("MainWindow", "Género"))
        self.label_7.setText(_translate("MainWindow", "Fecha de nacimiento"))
        self.label_8.setText(_translate("MainWindow", "Teléfono"))
        self.label_9.setText(_translate("MainWindow", "Edad"))
        self.clean.setText(_translate("MainWindow", "Limpiar"))
        self.menuOpciones.setTitle(_translate("MainWindow", "Opciones"))

