# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'agregarpaciente.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(806, 570)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.send = QtGui.QPushButton(self.centralWidget)
        self.send.setGeometry(QtCore.QRect(180, 400, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.send.setFont(font)
        self.send.setStyleSheet(_fromUtf8("background-color: rgb(220, 220, 220);"))
        self.send.setObjectName(_fromUtf8("send"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(340, 40, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(570, 130, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(30, 160, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(30, 200, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(550, 240, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gender = QtGui.QComboBox(self.centralWidget)
        self.gender.setGeometry(QtCore.QRect(630, 240, 111, 27))
        self.gender.setObjectName(_fromUtf8("gender"))
        self.dateEdit = QtGui.QDateEdit(self.centralWidget)
        self.dateEdit.setGeometry(QtCore.QRect(190, 240, 191, 27))
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.label_7 = QtGui.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(30, 240, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.ti = QtGui.QComboBox(self.centralWidget)
        self.ti.setGeometry(QtCore.QRect(600, 120, 141, 31))
        self.ti.setStyleSheet(_fromUtf8("border-color: rgb(0, 0, 0);"))
        self.ti.setObjectName(_fromUtf8("ti"))
        self.label_8 = QtGui.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(30, 280, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.spinBox = QtGui.QSpinBox(self.centralWidget)
        self.spinBox.setGeometry(QtCore.QRect(440, 240, 101, 31))
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.label_9 = QtGui.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(390, 240, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.clean = QtGui.QPushButton(self.centralWidget)
        self.clean.setGeometry(QtCore.QRect(490, 400, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.clean.setFont(font)
        self.clean.setStyleSheet(_fromUtf8("background-color: rgb(226, 226, 226);\n"
""))
        self.clean.setObjectName(_fromUtf8("clean"))
        self.idp = QtGui.QTextEdit(self.centralWidget)
        self.idp.setGeometry(QtCore.QRect(120, 120, 441, 31))
        self.idp.setStyleSheet(_fromUtf8("border-color: rgb(0, 0, 0);"))
        self.idp.setObjectName(_fromUtf8("idp"))
        self.name = QtGui.QTextEdit(self.centralWidget)
        self.name.setGeometry(QtCore.QRect(120, 160, 621, 31))
        self.name.setObjectName(_fromUtf8("name"))
        self.last = QtGui.QTextEdit(self.centralWidget)
        self.last.setGeometry(QtCore.QRect(120, 200, 621, 31))
        self.last.setObjectName(_fromUtf8("last"))
        self.phone = QtGui.QTextEdit(self.centralWidget)
        self.phone.setGeometry(QtCore.QRect(120, 280, 261, 31))
        self.phone.setObjectName(_fromUtf8("phone"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 806, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuOpciones = QtGui.QMenu(self.menuBar)
        self.menuOpciones.setObjectName(_fromUtf8("menuOpciones"))
        MainWindow.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menuOpciones.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Agregar paciente", None))
        self.send.setText(_translate("MainWindow", "Enviar", None))
        self.label.setText(_translate("MainWindow", "Paciente", None))
        self.label_3.setText(_translate("MainWindow", "TI", None))
        self.label_4.setText(_translate("MainWindow", "Nombres", None))
        self.label_5.setText(_translate("MainWindow", "Apellidos", None))
        self.label_6.setText(_translate("MainWindow", "Género", None))
        self.label_7.setText(_translate("MainWindow", "Fecha de nacimiento", None))
        self.label_8.setText(_translate("MainWindow", "Teléfono", None))
        self.label_9.setText(_translate("MainWindow", "Edad", None))
        self.clean.setText(_translate("MainWindow", "Limpiar", None))
        self.menuOpciones.setTitle(_translate("MainWindow", "Opciones", None))

