# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'agregarpaciente.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(517, 448)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.send = QtWidgets.QPushButton(self.centralWidget)
        self.send.setGeometry(QtCore.QRect(40, 300, 141, 61))
        self.send.setObjectName("send")
        self.idp = QtWidgets.QLineEdit(self.centralWidget)
        self.idp.setGeometry(QtCore.QRect(100, 120, 221, 27))
        self.idp.setObjectName("idp")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(210, 40, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(30, 120, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(330, 120, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(30, 160, 61, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.name = QtWidgets.QLineEdit(self.centralWidget)
        self.name.setGeometry(QtCore.QRect(100, 160, 221, 27))
        self.name.setObjectName("name")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(30, 200, 61, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lastname = QtWidgets.QLineEdit(self.centralWidget)
        self.lastname.setGeometry(QtCore.QRect(100, 200, 221, 27))
        self.lastname.setObjectName("lastname")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(330, 160, 41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gender = QtWidgets.QComboBox(self.centralWidget)
        self.gender.setGeometry(QtCore.QRect(380, 160, 111, 27))
        self.gender.setObjectName("gender")
        self.dateEdit = QtWidgets.QDateEdit(self.centralWidget)
        self.dateEdit.setGeometry(QtCore.QRect(160, 240, 161, 27))
        self.dateEdit.setObjectName("dateEdit")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(30, 240, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.ti = QtWidgets.QComboBox(self.centralWidget)
        self.ti.setGeometry(QtCore.QRect(350, 120, 141, 31))
        self.ti.setObjectName("ti")
        self.ti.addItem("")
        self.phone = QtWidgets.QLineEdit(self.centralWidget)
        self.phone.setGeometry(QtCore.QRect(390, 200, 101, 27))
        self.phone.setText("")
        self.phone.setObjectName("phone")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(330, 200, 61, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.spinBox = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox.setGeometry(QtCore.QRect(390, 240, 101, 22))
        self.spinBox.setObjectName("spinBox")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(330, 240, 31, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.send_2 = QtWidgets.QPushButton(self.centralWidget)
        self.send_2.setGeometry(QtCore.QRect(310, 300, 141, 61))
        self.send_2.setObjectName("send_2")
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 517, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuOpciones = QtWidgets.QMenu(self.menuBar)
        self.menuOpciones.setObjectName("menuOpciones")
        MainWindow.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menuOpciones.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Agregar paciente"))
        self.send.setText(_translate("MainWindow", "Enviar"))
        self.label.setText(_translate("MainWindow", "Paciente"))
        self.label_2.setText(_translate("MainWindow", "Documento"))
        self.label_3.setText(_translate("MainWindow", "TI"))
        self.label_4.setText(_translate("MainWindow", "Nombres"))
        self.label_5.setText(_translate("MainWindow", "Apellidos"))
        self.label_6.setText(_translate("MainWindow", "Género"))
        self.label_7.setText(_translate("MainWindow", "Fecha de nacimiento"))
        self.ti.setItemText(0, _translate("MainWindow", "Cédula de ciudadania"))
        self.label_8.setText(_translate("MainWindow", "Teléfono"))
        self.label_9.setText(_translate("MainWindow", "Edad"))
        self.send_2.setText(_translate("MainWindow", "Limpiar"))
        self.menuOpciones.setTitle(_translate("MainWindow", "Opciones"))

